server:
  port: 8080
#  max-http-header-size: 10000000

spring:
  #引入其他配置文件，格式:application-{xxx}.yml
  profiles:
    include:
      - druid
      - redis
      - mybatis
  # jackson时间格式化
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传大小控制
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB









