wx:
  pay:
    appId: wxbbe4f3bd3934bd01 #微信公众号或者小程序等的appid
    mchId: 1493345252 #微信支付商户号
    mchKey: 256235486qhkuolkjsjpq128635489er #微信支付商户密钥（apikey）
#    subAppId: #服务商模式下的子商户公众账号ID
#    subMchId: #服务商模式下的子商户号
#    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）

#微信公众号
gzh:
  appid: xxx
  secret: xxxxxx
  mchid: xxx
  apiKey: xxx

  #微信小程序
xcx:
  appid: xxx
  secret: xxx
  mchid: xxx
  apiKey: xxx
